http:
  host: "localhost"
  port: "8081"
  
database:
  host: "localhost"
  port: "3306" 
  user: "root"
  password: "root"

jms:
  Username: "admin"
  Client id: "admin"
 
log:
  message: "Welcome to CICD Process" 
 
deployment:
  app:
    runtime: "4.9.0"
  region: "us-east-2"         
  workers: "1"
  workerType: "MICRO"